"""Minimal numpy stub for mypy — see pyproject.toml mypy section.

Py3.14 runtime + numpy 2.5+ has stub using PEP 695 ``type`` statement which
mypy 1.10 cannot parse. This stub provides just enough typing for our project
imports (akshare etc. only need ``ndarray`` / ``float`` / DType). Real numpy
runtime is still used at execution time.
"""

# 来自 akshare 间接依赖的最小类型
from typing import Any

class ndarray: ...
class dtype: ...
class generic: ...
class float64: ...
class int64: ...
class bool_: ...

# 项目代码可能用到的部分
def array(*args: Any, **kwargs: Any) -> ndarray: ...
def zeros(*args: Any, **kwargs: Any) -> ndarray: ...
def ones(*args: Any, **kwargs: Any) -> ndarray: ...
def empty(*args: Any, **kwargs: Any) -> ndarray: ...
def asarray(*args: Any, **kwargs: Any) -> ndarray: ...
def isclose(*args: Any, **kwargs: Any) -> bool: ...
def all(*args: Any, **kwargs: Any) -> bool: ...
def any(*args: Any, **kwargs: Any) -> bool: ...
def mean(*args: Any, **kwargs: Any) -> float: ...
def sum(*args: Any, **kwargs: Any) -> Any: ...
def max(*args: Any, **kwargs: Any) -> Any: ...
def min(*args: Any, **kwargs: Any) -> Any: ...
def abs(*args: Any, **kwargs: Any) -> Any: ...
def nan(*args: Any, **kwargs: Any) -> float: ...
def inf(*args: Any, **kwargs: Any) -> float: ...
def isfinite(*args: Any, **kwargs: Any) -> ndarray: ...
def isnan(*args: Any, **kwargs: Any) -> ndarray: ...
def where(*args: Any, **kwargs: Any) -> ndarray: ...

# 子模块 stub
class _Module:
    def __getattr__(self, name: str) -> Any: ...

class _NumpyModule:
    def __getattr__(self, name: str) -> Any: ...

# 顶层引用
ndarray = ndarray
dtype = dtype

# 暴露常用子模块（让 from numpy import X 不报错）
typing: _Module = _Module()
core: _Module = _Module()
lib: _Module = _Module()
random: _Module = _Module()
testing: _Module = _Module()
version: _Module = _Module()
ma: _Module = _Module()
rec: _Module = _Module()
char: _Module = _Module()
financial: _Module = _Module()
compat: _Module = _Module()
polynomial: _Module = _Module()
matrixlib: _Module = _Module()
ctypeslib: _Module = _Module()
distutils: _Module = _Module()
f2py: _Module = _Module()
fft: _Module = _Module()
linalg: _Module = _Module()
__version__: str = "2.5.1"
